<html><header><title>Catching exceptions in the UI</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Catching exceptions in the UI</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/1263.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>albruan posted on Tuesday, September 19, 2006</h2><P><FONT face=Arial>I have a couple of questions regarding returning errors to the UI.&nbsp; I&nbsp;instantiated and populated five new Drawing objects, deliberately setting one of them to use the same DeptID and DrawingCode as a Drawing object that had previously been persisted to the database, and attempted to save the objects.&nbsp; As expected, an exception was thrown by SQL Server since I have a unique index set on the Drawings table based on the DeptID and DrawingCode.&nbsp; If I place the call to&nbsp;the Save method&nbsp;in a Try...Catch block and catch the DataPortalException,&nbsp;I get a "Cannot insert duplicate key row in object 'dbo.Drawings' with unique index 'DrawingCode'." message in the UI.&nbsp; </FONT></P>
<P><FONT face=Arial>How do I go about informing the user which entry caused the exception to be thrown?&nbsp; Is there a way to catch the error prior to calling the Save method?&nbsp; I thought about possibly using a variation of the Contains method and will look into it this evening as I have two appointments to keep today which will take up the balance of my day.&nbsp; </FONT></P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>ajj3085 replied on Tuesday, September 19, 2006</h2>I think you're stuck examining the message; unfortunately there's not just enough detail in SqlException to help you determine which object caused the error.<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>skagen00 replied on Tuesday, September 19, 2006</h2><P>In my base class I catch SqlException, test the code, and throw a custom exception (such as ConcurrencyException).</P>
<P>So if you want to give a more useful exception to the UI layer, wrap data access, catch exceptions, and rethrow as either custom exceptions (if they match certain categories you want to throw) or rethrow as the original exception. </P>
<P>&nbsp;</P></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
