<html><header><title>MethodCaller bug?</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>MethodCaller bug?</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/5411.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>GlennMiller posted on Tuesday, September 16, 2008</h2><P>Hi,</P>
<P>We're trying out Csla CE and have found what we think is a problem in CslaCE.MethodCaller.CallMethod. The catch there throws a new CallMethodException, passing ex..InnerException. As noted in this thread, <A HREF="/forums/thread/21707.aspx">http://forums.lhotka.net/forums/thread/21707.aspx</A>, this is how Rocky got to the exception in Csla 3.0. The thread points out that the exception of interest is wrapped in a reflection exception, so accessing the InnerException property gets back to the original exception.</P>
<P>However, we're noticing in all our tests that if an exception happens on the "back" side of the DataPortal methods (like DataPortal_Fetch), the exception that ends up in MethodCaller.CallMethod is *not* wrapped. In fact the InnerException property is null, so Csla crashes later in CallMethodException's constructor.</P>
<P>We're assuming that the "ce-ifying" of the code removed the reflection wrapper, so we fixed the problem by changing CallMethod to pass on the exception itself, not its innerexception. Sound right?</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>lawrencek replied on Tuesday, September 23, 2008</h2><P>Please post this also.&nbsp; Also thanks for working on the data portal calls..</P>
<P>I have not been using them and have been tring to fill them out as much a CE will allow.</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>GlennMiller replied on Tuesday, September 30, 2008</h2>Here's the method from MethodCaller.cs. We commented out the InnerException as shown.<br /><br />/// <br />/// Uses reflection to dynamically invoke a method,<br />/// throwing an exception if it is not<br />/// implemented on the target object.<br />/// <br />public static object CallMethod(<br />  object obj, MethodInfo info, params object[] parameters)<br />{<br />    // call a private method on the object<br />    object result;<br />    try<br />    {<br />        result = info.Invoke(obj, parameters);<br />    }<br />    catch (Exception e)<br />    {<br />        throw new Csla.Server.CallMethodException(<br />           info.Name + " " + Resources.MethodCallFailed, e/*.InnerException*/);<br />    }<br />    return result;<br />}<br /><br /></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
