<html><header><title>CslaActionExtender and exception during Save</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>CslaActionExtender and exception during Save</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/5613.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>detritus posted on Friday, October 17, 2008</h2>I don't know if this is by-design or a bug: If I got an exception during save operation while using CslaActionExtender, binding source's datasource becomes null. I think making datasource null is on purpose but not to be able from an exception and put old datasource back may be a bug).<br><br>For now, I got around this by handling ErrorEncountered event and do a rebind there with the BO reference I hold in a private field, is this the expected behaviour / recommended method?<br><br>Thanks,<br>Sinan<br></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
