<html><header><title>Async Data Access Exceptions</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>Async Data Access Exceptions</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/6205.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>TAC posted on Monday, January 19, 2009</h2>Ok, my factory methods are Async. When one of my Data Access methods throws an exception ("Can't find data", etc) when it gets to Fetch_RunWorkerCompleted the line<br>var result = e.Result as DataPortalAsyncResult;<br>throws an TargetInvocationException (more specifically e.Result throws it)<br>and because of that My Method for OnFetchCompleted is never getting run.<br><br>This seems like a bug to me or is my process wrong?<br><br>(Quick note: this is all dotNet not silverlight)<br></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Tuesday, January 20, 2009</h2><P>Thanks for finding this, it is a bug and I'll add it to the list.</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Tuesday, January 20, 2009</h2><P>I fixed this for 3.6.1, and the fix is in svn. If you can grab the latest code</P>
<P><A href="http://www.lhotka.net/cslacvs/viewvc.cgi/trunk/cslacs/Csla/DataPortalT.cs?view=log">http://www.lhotka.net/cslacvs/viewvc.cgi/trunk/cslacs/Csla/DataPortalT.cs?view=log</A></P>
<P>and give it a try that'd be great!</P></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>TAC replied on Tuesday, January 20, 2009</h2>Thanks for that Rocky. My solution was using a try-catch block. Same result but your way is much nicer.<br></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
