<html><header><title>ChildDataPortal.Create fails to instantiate exception</title></header><body><div style='float:right'><a href='http://cslanet.com'><img src='https://github.com/MarimerLLC/csla/raw/master/Support/Logos/csla%20win8_compact_s.png'/></a></div><p><h1>ChildDataPortal.Create fails to instantiate exception</h1><span style='font-size:small'>Old forum URL: forums.lhotka.net/forums/t/8828.aspx</span></p><hr><div style='padding:0 15 3 15;background-color:powderblue'><h2>nelis posted on Thursday, April 22, 2010</h2><p>When create of a child object fails (in my case by an exception thrown in AddBusinessRules), the catch in ChildDataPortal.Create is executed. When both &#39;target&#39; and &#39;obj&#39; are null the throw Exception statement itself throws a null reference exception because it references obj.Instance. </p>
<p>This makes debugging very difficult and should be fixed.</p>
<p>I am using 3.8.1. Couldn&#39;t find any previous posts about this.</p></div><div style='padding:0 15 3 15;background-color:lightgreen'><h2>RockfordLhotka replied on Thursday, April 22, 2010</h2><p>I see what you mean - that is not good, and I&#39;ll add it to the bug list. Thanks!</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>nelis replied on Monday, July 26, 2010</h2><p>This bug is still in 3.8.4 and 4.0.0</p></div><div style='padding:0 15 3 15;background-color:powderblue'><h2>RockfordLhotka replied on Monday, July 26, 2010</h2><p>I see the issue too, I&#39;ll reopen the bug.</p></div><p style='font-size:small'>Copyright (c) Marimer LLC</body></html>
